### StandardScaler centers and scales each feature in the dataseta

In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Example dataset
data = np.array([[1.0, 3.5, -2.2, 6.1],
                 [0.5, -1.2, 4.3, -3.6],
                 [3.4, 1.8, 0.5, 2.0]])

# Create a StandardScaler object
scaler = StandardScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)

# The scaled data
print("Scaled Data:\n", scaled_data)

# The mean of each feature after scaling (should be close to 0)
print("Mean of each feature after scaling:\n", scaled_data.mean(axis=0))

# The standard deviation of each feature after scaling (should be 1)
print("Standard Deviation of each feature after scaling:\n", scaled_data.std(axis=0))


Scaled Data:
 [[-0.50034662  1.09791391 -1.15017973  1.15701152]
 [-0.89535711 -1.32092767  1.28770122 -1.28277365]
 [ 1.39570373  0.22301376 -0.13752149  0.12576212]]
Mean of each feature after scaling:
 [-2.22044605e-16  1.94289029e-16 -7.40148683e-17 -3.70074342e-17]
Standard Deviation of each feature after scaling:
 [1. 1. 1. 1.]


In [2]:
amean = scaled_data.mean(axis=0)
np.around(amean, decimals = 0)

array([-0.,  0., -0., -0.])

In [3]:
amean

array([-2.22044605e-16,  1.94289029e-16, -7.40148683e-17, -3.70074342e-17])

### Centering data is subtracting the mean from each observation

In [4]:
# Example dataset
data = np.array([[1.0, 3.5, -2.2, 6.1],
                 [0.5, -1.2, 4.3, -3.6],
                 [3.4, 1.8, 0.5, 2.0]])

# Calculate the mean of each feature
mean_values = np.mean(data, axis=0)

# Center the data by subtracting the mean of each feature
centered_data = data - mean_values

# The centered data
print("Centered Data:\n", centered_data)

# The mean of each feature after centering (should be close to 0)
centered_data_mean = centered_data.mean(axis=0)
print("Mean of each feature after centering:\n", np.around(centered_data_mean))#,decimals=0))

Centered Data:
 [[-0.63333333  2.13333333 -3.06666667  4.6       ]
 [-1.13333333 -2.56666667  3.43333333 -5.1       ]
 [ 1.76666667  0.43333333 -0.36666667  0.5       ]]
Mean of each feature after centering:
 [-0.  0. -0.  0.]


### Scaling is to adjust the range of your data without changing its central location (mean)
### MinMaxScaler adjust the range to 0-1

In [24]:
from sklearn.preprocessing import MinMaxScaler

# Example dataset
data = np.array([[1.0, 3.5, -2.2, 6.1],
                 [0.5, -1.2, 4.3, -3.6],
                 [3.4, 1.8, 0.5, 2.0]])

# Create a MinMaxScaler object for scaling between 0 and 1
scaler = MinMaxScaler(feature_range=(0, 1))

# Fit and transform the data
scaled_data = scaler.fit_transform(data)

# The scaled data
print("Scaled Data:\n", np.around(scaled_data,decimals=2))

Scaled Data:
 [[0.17 1.   0.   1.  ]
 [0.   0.   1.   0.  ]
 [1.   0.64 0.42 0.58]]
